name: Convert Tiny Builder
on: [ workflow_dispatch ]
env:
  BUILDER: "paketobuildpacks/builder:tiny"
  BUILDER_DIR: "builders/paketobuildpacks/builder:tiny"
  OCI_IMAGE_PREFIX: "docker.io/maliksalman"

jobs:

  check:
    runs-on: [self-hosted, Linux, ARM64]
    outputs:
      status: ${{ steps.check.outputs.status }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: get-manifest
        run: |
          mkdir -p $BUILDER_DIR
          pack builder inspect $BUILDER -o json | jq .remote_info > "$BUILDER_DIR/info.json"
      - id: check
        run: |
          CHANGED=$(git diff --exit-code --output=/dev/null "$BUILDER_DIR/info.json"; echo $?)
          if [[ $CHANGED -eq 0 ]]; then
              echo "Nothing changed since last conversion"
              echo "status=skip" >> $GITHUB_OUTPUT
          else
              echo "Something changed, we will perform the conversion"
              echo "status=convert" >> $GITHUB_OUTPUT
          fi

  convert:
    runs-on: [self-hosted, Linux, ARM64]
    needs: [check]
    if: needs.check.outputs.status == 'convert'
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: start-fixer
        run: |
          CACHE_DIR=".work/cache"
          mkdir -p $CACHE_DIR
          echo "Cache: $PWD/$CACHE_DIR"
          docker rm -f buildpacks-manifest-fixer 2> /dev/null
          docker run -d \
              --name buildpacks-manifest-fixer \
              -e CONFIG_ARTIFACTSHACACHEDIR=/workspace/cache \
              -e CONFIG_IMAGEPREFIX=$OCI_IMAGE_PREFIX \
              -v $PWD/$CACHE_DIR:/workspace/cache \
              --user $(id -u):$(id -g) \
              -p 58585:8080 \
              maliksalman/buildpacks-manifest-fixer:1.0.0-arm64
      - id: clone-buildpacks
        run: |
          for BP in $(jq '.buildpacks[] | {id,version}' -c $BUILDER_DIR/info.json); do
            BP_ID=$(echo "$BP" | jq -r ".id")
            BP_VER=$(echo "$BP" | jq -r ".version")
            ./clone-buildpack.sh "$BP_ID" "$BP_VER" ".work/buildpacks"
          done
      - id: convert-simple-buildpacks
        run: |
          for BP in $(jq '.buildpacks[] | {id,version}' -c $BUILDER_DIR/info.json); do
            BP_ID=$(echo "$BP" | jq -r ".id")
            BP_VER=$(echo "$BP" | jq -r ".version")
            ./convert-buildpack.sh "$BP_ID" "$BP_VER" .work/buildpacks false $OCI_IMAGE_PREFIX
          done
      - id: convert-composite-buildpacks
        run: |
          for BP in $(jq '.buildpacks[] | {id,version}' -c $BUILDER_DIR/info.json); do
            BP_ID=$(echo "$BP" | jq -r ".id")
            BP_VER=$(echo "$BP" | jq -r ".version")
            ./convert-buildpack.sh "$BP_ID" "$BP_VER" .work/buildpacks true $OCI_IMAGE_PREFIX
          done
      - id: stop-fixer
        run: |
          docker rm -f buildpacks-manifest-fixer 2> /dev/null
      
  version:
    runs-on: [self-hosted, Linux, ARM64]
    needs: [check]
    if: needs.check.outputs.status == 'convert'
    outputs:
      VERSION: ${{ steps.bump-semver.outputs.new_version }}
      STACK_ID: ${{ steps.idnames.outputs.STACK_ID }}
      STACK_RUN_IMAGE: ${{ steps.idnames.outputs.STACK_RUN_IMAGE }}
      STACK_BUILD_IMAGE: ${{ steps.idnames.outputs.STACK_BUILD_IMAGE }}
    steps:
      - id: existing-version
        run: |
          EXISTING_VER=$(cat $BUILDER_DIR/version)
          echo "EXISTING_VER=$EXISTING_VER" >> $GITHUB_ENV
      - id: bump-semver
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ env.EXISTING_VER }}
          level: minor
      - id: idnames
        env:
          VERSION: ${{ steps.bump-semver.outputs.new_version }}
        run: |
          echo "$VERSION" > $BUILDER_DIR/version

          STACK_ID="$(jq '.stack.id' $BUILDER_DIR/info.json -r)"
          STACK_IMAGES_PREFIX=$(echo $BUILDER | sed 's|\(.*\)/\(.*\):\(.*\)|\1-\2-\3|')
          STACK_RUN_IMAGE="$OCI_IMAGE_PREFIX/$STACK_IMAGES_PREFIX-run:arm64-$VERSION"
          STACK_BUILD_IMAGE="$OCI_IMAGE_PREFIX/$STACK_IMAGES_PREFIX-build:arm64-$VERSION"

          echo "STACK_ID=$STACK_ID" >> $GITHUB_OUTPUT
          echo "STACK_RUN_IMAGE=$STACK_RUN_IMAGE" >> $GITHUB_OUTPUT
          echo "STACK_BUILD_IMAGE=$STACK_BUILD_IMAGE" >> $GITHUB_OUTPUT

  stack:
    runs-on: [self-hosted, Linux, ARM64]
    needs: [check, version]
    if: needs.check.outputs.status == 'convert'
    env:
      STACK_ID: ${{ needs.version.outputs.STACK_ID }}
      STACK_RUN_IMAGE: ${{ needs.version.outputs.STACK_RUN_IMAGE }}
      STACK_BUILD_IMAGE: ${{ needs.version.outputs.STACK_BUILD_IMAGE }}
    steps:
      - id: stack-build
        run: |
          docker build . \
              -t  $STACK_RUN_IMAGE \
              --build-arg STACK_ID="$STACK_ID" \
              --target run
      - id: stack-run
        run: |
          docker build . \
              -t $STACK_BUILD_IMAGE \
              --build-arg STACK_ID="$STACK_ID" \
              --target build
      - id: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - id: publish
        run: |
          echo docker push $STACK_RUN_IMAGE
          echo docker push $STACK_BUILD_IMAGE